title: My PhD
author:
  name: Floriane Chiffoleau

# The `>` after `description:` means to ignore line-breaks until next key.
# If you want to omit the line-break after the end of text, use `>-` instead.
description: >
  This website reports the experiences, readings and others activities 
  I am currently doing as part of my PhD.
# Build settings

theme: minima


plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Theme-specific settings

minima:
  # Minima date format.
  # Refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this.
  #
  date_format: "%b %-d, %Y"

  # Generate social links in footer.
  #
  social_links:
  - { platform: github,         user_url: "https://github.com/FloChiff" }
  - { platform: linkedin,       user_url: "https://www.linkedin.com/in/floriane-chiffoleau-8ba868196/" }
  - { platform: twitter,        user_url: "https://twitter.com/MissBrutus" }

# If you want to link only specific pages in your header, uncomment this and add the path to the pages in
# order as they should show up.
#
  header_pages:
  - notes/bibliography.md
  - notes/glossary.md

# Set to `true` to show excerpts on the homepage.
#
show_excerpts: false